-- Insert all 81 clients into the clients table
-- Run this SQL in phpMyAdmin

INSERT IGNORE INTO clients (client_name, is_active) VALUES 
('Confidence Infrastructure Ltd.(ZDL)', 1),
('M/S Saleh Ahmed', 1),
('Sigma engineers Ltd', 1),
('Confidence Infrastructure Ltd(EPC-1)', 1),
('M/S Amir Engineering Corporation', 1),
('TEESTA SOLAR LIMITED', 1),
('MD. FRIDUL ISLAM', 1),
('M/S LUCKY CONSTRUCTION', 1),
('M/S GOLDER TRADING CORP.', 1),
('Grameen Trade International', 1),
('M/S. Masuma Begum', 1),
('M/S.M.R. Construction', 1),
('Sulekhasons Limited', 1),
('M/S. Shaju Hardware', 1),
('S.S. Rahman International Ltd', 1),
('Bengal Structure Development Ltd - Future Infrastructure Development Ltd. (Joint venture)', 1),
('OTJ Joint Venture', 1),
('NATIONAL DEVELOPMENT ENGINEERS LTD.', 1),
('Azmirr Builders Limited', 1),
('M/S SK Emdadul Haque Al Mamun', 1),
('M/S. Zinnat Ali Zinnah Limited', 1),
('MIR AKHTER - WMCG JV', 1),
('GOLAM RABBANI CONSTRUCTION LTD.', 1),
('ZINNAT ALI ZINNAH LIMITED', 1),
('SK.Emdadul Haque Al-Mamun', 1),
('Confidence Infrastructure Limited (EPC-3)', 1),
('HUDA TRADERS', 1),
('M/S. MOSTAFA & SONS', 1),
('ATAUR RAHMAN KHAN LTD.', 1),
('Samuda Construction Ltd.', 1),
('BISWAS TRADING & CONSTRUCTION', 1),
('Confidence Infrastructure Ltd.(CIL-Dredging Unit)', 1),
('Orient Trading & Builders Ltd.', 1),
('Tajwar Trade System Ltd', 1),
('M/S AMIR HOSSEN TRADERS', 1),
('CREATIVE ENGINEERS LTD.', 1),
('BRAC', 1),
('HUDA HOLDINGS LIMITED', 1),
('Nahee Geotextile Ltd.', 1),
('Orchid Geotextile Ltd', 1),
('Hassan & Brothers', 1),
('DIRD Felt Limited', 1),
('M/s. Ahad Builders', 1),
('M/S.SHUKTARA CONSTRUCTION', 1),
('Project Director, PMO-FRERMIP, BWDB, Dhaka', 1),
('ARC Construction Company', 1),
('BALY SHRIMP HATCHERY', 1),
('Excel Construction', 1),
('M/S .khandaker shahin ahmed', 1),
('S.S Engineering & Construction Ltd.', 1),
('M/S. Sokina & Sons', 1),
('M/S.AR-R\'AD Corporation', 1),
('Eagle Ridge Engineering & Construction (BD) Ltd.', 1),
('SWAN INTERNATIONAL (PVT.) LIMITED', 1),
('M/S Sarika Traders', 1),
('Nation Tech Communication Limited', 1),
('Bengal Group of Industries', 1),
('MASTERMIND ENGINEERING LTD.', 1),
('Alam & Brothers', 1),
('M.M. Builders & Engineers LTD', 1),
('Property Development Ltd', 1),
('KCEL-BECL JV', 1),
('CASTLE CONSTRUCTION CO. LIMITED', 1),
('Standard Engineers LTD', 1),
('M/S Rasa Enterprise', 1),
('First S.S Enterprise (Pvt.) Ltd.', 1),
('CROSSIFIC CONSTRUCTION', 1),
('BAY DREDGERS LIMITED', 1),
('Future Infrastructure Development Ltd.', 1),
('Sazzad Hossain', 1),
('BIFEX ENGINEERING', 1),
('Md. Ataur Rahman', 1),
('Energypac Infrastructure & Development Ltd', 1),
('Bismillahi Engineering Corporation Limited', 1),
('Md. Afaz Uddin', 1),
('M/S Masud Trading Corporation', 1),
('Shahin Sharif', 1),
('IRA Enterprise', 1),
('Al-Mostafa Group', 1),
('Confidence Cement Dhaka Ltd', 1),
('TEKKEN CORPORATION', 1);
